// <auto-generated />
using System;
using FundRaiser.Team5.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FundRaiser.Team5.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FundRaiser.Team5.Core.Entities.FundingPackage", b =>
                {
                    b.Property<int>("FundingPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MinPrice")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfAvailablePackages")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FundingPackageId");

                    b.HasIndex("ProjectId");

                    b.ToTable("FundingPackages");
                });

            modelBuilder.Entity("FundRaiser.Team5.Core.Entities.ImagePath", b =>
                {
                    b.Property<int>("ImagePathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("ImagePathId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ImagePaths");
                });

            modelBuilder.Entity("FundRaiser.Team5.Core.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentFund")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FundingGoal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("FundRaiser.Team5.Core.Entities.StatusUpdate", b =>
                {
                    b.Property<int>("StatusUpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeUploaded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusUpdateId");

                    b.HasIndex("ProjectId");

                    b.ToTable("StatusUpdates");
                });

            modelBuilder.Entity("FundRaiser.Team5.Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FundRaiser.Team5.Core.Entities.UserFundingPackage", b =>
                {
                    b.Property<int>("UserFundingPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FundingPackageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserFundingPackageId");

                    b.HasIndex("FundingPackageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFundingPackages");
                });

            modelBuilder.Entity("FundRaiser.Team5.Core.Entities.VideoPath", b =>
                {
                    b.Property<int>("VideoPathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Video")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VideoPathId");

                    b.HasIndex("ProjectId");

                    b.ToTable("VideoPaths");
                });

            modelBuilder.Entity("FundRaiser.Team5.Core.Entities.FundingPackage", b =>
                {
                    b.HasOne("FundRaiser.Team5.Core.Entities.Project", "Project")
                        .WithMany("FundingPackages")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FundRaiser.Team5.Core.Entities.ImagePath", b =>
                {
                    b.HasOne("FundRaiser.Team5.Core.Entities.Project", null)
                        .WithMany("Images")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("FundRaiser.Team5.Core.Entities.Project", b =>
                {
                    b.HasOne("FundRaiser.Team5.Core.Entities.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FundRaiser.Team5.Core.Entities.StatusUpdate", b =>
                {
                    b.HasOne("FundRaiser.Team5.Core.Entities.Project", "Project")
                        .WithMany("StatusUpdates")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FundRaiser.Team5.Core.Entities.UserFundingPackage", b =>
                {
                    b.HasOne("FundRaiser.Team5.Core.Entities.FundingPackage", "FundingPackage")
                        .WithMany("UserFundingPackages")
                        .HasForeignKey("FundingPackageId");

                    b.HasOne("FundRaiser.Team5.Core.Entities.User", "User")
                        .WithMany("UserFundingPackages")
                        .HasForeignKey("UserId");

                    b.Navigation("FundingPackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FundRaiser.Team5.Core.Entities.VideoPath", b =>
                {
                    b.HasOne("FundRaiser.Team5.Core.Entities.Project", null)
                        .WithMany("Videos")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("FundRaiser.Team5.Core.Entities.FundingPackage", b =>
                {
                    b.Navigation("UserFundingPackages");
                });

            modelBuilder.Entity("FundRaiser.Team5.Core.Entities.Project", b =>
                {
                    b.Navigation("FundingPackages");

                    b.Navigation("Images");

                    b.Navigation("StatusUpdates");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("FundRaiser.Team5.Core.Entities.User", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("UserFundingPackages");
                });
#pragma warning restore 612, 618
        }
    }
}
