// <auto-generated />
using System;
using FundRaiser_Team5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FundRaiser_Team5.Migrations
{
    [DbContext(typeof(FrDbContext))]
    [Migration("20210525122202_FundRaiser")]
    partial class FundRaiser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FundRaiser_Team5.BackerFundingPackage", b =>
                {
                    b.Property<int>("BackerFundingPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BackerFundingPackageStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FundingPackageId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BackerFundingPackageId");

                    b.HasIndex("FundingPackageId");

                    b.HasIndex("UserId");

                    b.ToTable("backerFundingPackages");
                });

            modelBuilder.Entity("FundRaiser_Team5.Model.FundingPackage", b =>
                {
                    b.Property<int>("FundingPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvailablePackages")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinPrice")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FundingPackageId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("FundingPackages");
                });

            modelBuilder.Entity("FundRaiser_Team5.Model.ImagePath", b =>
                {
                    b.Property<int>("ImagePathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("ImagePathId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ImagePaths");
                });

            modelBuilder.Entity("FundRaiser_Team5.Model.VideoPath", b =>
                {
                    b.Property<int>("VideoPathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Video")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VideoPathId");

                    b.HasIndex("ProjectId");

                    b.ToTable("VideoPaths");
                });

            modelBuilder.Entity("FundRaiser_Team5.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentFund")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FundingGoal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("FundRaiser_Team5.StatusUpdate", b =>
                {
                    b.Property<int>("StatusUpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeUploaded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusUpdateId");

                    b.HasIndex("ProjectId");

                    b.ToTable("StatusUpdates");
                });

            modelBuilder.Entity("FundRaiser_Team5.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FundRaiser_Team5.BackerFundingPackage", b =>
                {
                    b.HasOne("FundRaiser_Team5.Model.FundingPackage", "FundingPackage")
                        .WithMany("BackerFundingPackages")
                        .HasForeignKey("FundingPackageId");

                    b.HasOne("FundRaiser_Team5.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("FundingPackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FundRaiser_Team5.Model.FundingPackage", b =>
                {
                    b.HasOne("FundRaiser_Team5.Project", "Project")
                        .WithMany("FundingPackages")
                        .HasForeignKey("ProjectId");

                    b.HasOne("FundRaiser_Team5.User", null)
                        .WithMany("FundingPackage")
                        .HasForeignKey("UserId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FundRaiser_Team5.Model.ImagePath", b =>
                {
                    b.HasOne("FundRaiser_Team5.Project", null)
                        .WithMany("Photos")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("FundRaiser_Team5.Model.VideoPath", b =>
                {
                    b.HasOne("FundRaiser_Team5.Project", null)
                        .WithMany("Videos")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("FundRaiser_Team5.Project", b =>
                {
                    b.HasOne("FundRaiser_Team5.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FundRaiser_Team5.StatusUpdate", b =>
                {
                    b.HasOne("FundRaiser_Team5.Project", "Project")
                        .WithMany("StatusUpdates")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FundRaiser_Team5.Model.FundingPackage", b =>
                {
                    b.Navigation("BackerFundingPackages");
                });

            modelBuilder.Entity("FundRaiser_Team5.Project", b =>
                {
                    b.Navigation("FundingPackages");

                    b.Navigation("Photos");

                    b.Navigation("StatusUpdates");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("FundRaiser_Team5.User", b =>
                {
                    b.Navigation("FundingPackage");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
